version: "3.9"
services:
  bind9:
    container_name: bind9
    image: internetsystemsconsortium/bind9:9.16
    ports:
      - 5300:53/udp
      - 5300:53/tcp
    volumes:
      - /home/dony/DNS/config:/etc/bind
      - /home/dony/DNS/zonas:/var/lib/bind
    networks:
      bind9_subnet:
        ipv4_address: 10.1.0.254
  asir_cliente:
    container_name: asir_cliente
    image: alpine
    networks: 
      - bind9_subnet
    stdin_open: true      # docker run -i 
    tty: true             # docker run -t , opciones para que se nos abra un nuevo ter
    dns: 
      - 10.1.0.254        #el contenedor dns server
networks:
 bind9_subnet: 
  external: true
                      
